.github/workflows/release.yml
src/actions/add-action.ts
src/actions/list-action.ts
src/actions/upgrade-action.ts
src/constants/component.ts
src/constants/required.ts
src/constants/store.ts
src/helpers/check.ts
src/helpers/package.ts
src/helpers/type.ts
src/helpers/upgrade.ts
src/index.ts
src/scripts/helpers.ts

fix: ci and compare vesion optimize cache

---

src/actions/doctor-action.ts
src/constants/required.ts
src/helpers/check.ts

1、Tailwind config error detech nextui plugin
close #27 
Add function object match in nextui plugin
2、Tailwind config error about Individual component content check
close #28 
Add warn if already have all include in tailwind config when using individual components
3、CLI component instalation ruined tailwind.config.js
close #29

fix(doctor): tailwind config error about content nextui plugin detech

---

src/actions/init-action.ts
src/constants/templates.ts
src/prompts/index.ts

feat: add project name prompt to init-action

---

src/actions/add-action.ts

feat: optimize output

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

@jrgarciadev please help create discussion in this repo.

feat(docs): add code of conduct, contributing and revise README info

---

src/actions/add-action.ts
src/actions/doctor-action.ts
src/helpers/check.ts
src/helpers/remove.ts

1、Add warn attention in add and remove command
Remove command
Add command
Both these woun't change the `./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}` let user know and change by himself
Doctor command
2、Optimize already installed output

feat: add warn attention in add and remove command

---

src/actions/upgrade-action.ts
src/helpers/package.ts
src/helpers/upgrade.ts

1、Upgrade command all option include others components
https://github.com/nextui-org/nextui-cli/assets/96854855/5957fb31-e3b2-49e2-b498-459c7f784bd5

refactor: upgrade command all option include others components

---

src/actions/init-action.ts
src/helpers/output-info.ts
src/prompts/index.ts

1、Add guide after init
https://github.com/nextui-org/nextui-cli/assets/96854855/91debe2a-a24b-448f-aea0-50ee36beb203

feat: init command add guide

---

src/helpers/output-info.ts
src/helpers/utils.ts

fix: output component lose alignment

---

src/helpers/remove.ts

feat: optimize removeDep type

---

.github/workflows/release.yml
package.json

ci: repair release

---

src/index.ts

feat: optimize warn output

---

README.md
package.json
pnpm-lock.yaml
src/actions/init-action.ts
src/constants/templates.ts
src/helpers/fix.ts
src/helpers/utils.ts
src/index.ts
src/prompts/clack.ts

1、npm
2、yarn
3、pnpm
Add .npmrc content when using pnpm
4、bun

feat(init): add package manager and use clack prompt instead

---

package.json
pnpm-lock.yaml
src/actions/upgrade-action.ts
src/prompts/index.ts

1.  Add display about disabled pkg when select omponents
Every up to date pkg show in bottom

feat: add sort disabled pkg when select compoents

---

src/actions/add-action.ts
src/actions/doctor-action.ts
src/helpers/check.ts
src/helpers/upgrade.ts

1、Less color with output
<p align="center">Before</p>
<p align="center">After</p>
2、Add peerDependencies check
relate: https://github.com/nextui-org/nextui/issues/2954

feat(doctor): add peerDependencies check and less color

---

README.md
src/actions/add-action.ts
src/actions/doctor-action.ts
src/helpers/check.ts
src/helpers/upgrade.ts

docs: update README

---

README.md
src/actions/init-action.ts
src/constants/templates.ts
src/helpers/type.ts

feat: add vite init template

---

src/scripts/update/update-components.ts

fix: add initCache in updateComponents script

---

.eslintrc
.prettierignore

fix: eslint error

---

.prettierignore
src/constants/components.json
src/helpers/fix.ts

fix: init vite template npmrc

---

.prettierignore
src/helpers/utils.ts

fix: upgrade peerDep error version

---

.prettierignore
package.json

Don't need commit changelog again

chore: optimize release flow

---

src/actions/upgrade-action.ts

Fix: https://discord.com/channels/856545348885676062/886605174162989068/1248305367436365875

fix: upgrade command select option cannot select @nextui-org/react pkg

---

src/actions/upgrade-action.ts

feat: optimize upgrade select options package name display

---

src/actions/init-action.ts
src/helpers/init.ts
src/helpers/math-diff.ts

1. init options check
- option template
- option package

feat: init command add invalid options check

---

package.json
pnpm-lock.yaml
src/actions/add-action.ts
src/actions/remove-action.ts
src/helpers/match.ts
src/index.ts

Fix add command error in tailwind.config.js
Link: https://discord.com/channels/856545348885676062/1249281814787395645
https://github.com/nextui-org/nextui-cli/assets/96854855/e5368571-49f6-4f0c-a6d0-040459fa09cd

fix: add command error in tailwind

---

README.md
src/actions/upgrade-action.ts
src/index.ts

closes #55
Added -w write option in upgrade command
-  Improvement (non-breaking change which improves an existing feature)
-  Documentation update

feat(upgrade): add -w write option to upgrade command

---

.github/workflows/sync.yml
README.md

Add a unique id for each run in branch to avoid branch exist issue

ci: sync error

---

package.json
pnpm-lock.yaml
src/actions/doctor-action.ts
src/actions/init-action.ts
src/constants/path.ts
src/constants/required.ts
src/helpers/detect.ts
src/scripts/path.ts

fix diff system path error
https://discord.com/channels/856545348885676062/856545348885676068/1258768263710773248

fix: path error in window

---

src/actions/add-action.ts
src/helpers/check.ts
src/helpers/logger.ts

fix: improve output readablility

---

package.json

Upon using the script `npm run lint:fix` it is failing due to a minor syntax error. 
|Before|After|
|---------|------|
|![image](https://github.com/user-attachments/assets/0225e762-79eb-41c1-90e3-0e8442556151)| ![image](https://github.com/user-attachments/assets/36eaaee9-9bd7-46e2-8679-028320dab341)|

fix(root): `lint:fix` script

---

package.json
pnpm-lock.yaml

fix: lock file

---

CHANGELOG.md

Release-0.3.3

---

src/actions/add-action.ts
src/constants/store.ts
src/helpers/debug.ts
src/helpers/fix.ts
src/helpers/match.ts
src/index.ts

fix: add debug mode and tailwindcss content mess repair

---

src/actions/init-action.ts
src/prompts/clack.ts

fix: rename issue

---

.github/workflows/release.yml
CHANGELOG.md
package.json

chore: release v0.3.5

---

.github/workflows/release.yml
package.json

fix: release node version

---

.github/workflows/release.yml
CHANGELOG.md

fix: release v0.3.5

---

src/helpers/match.ts

fix: remove quote

---

src/actions/init-action.ts
src/helpers/actions/init/change-npmrc.ts

fix: turn on the template npmrc lock file

---

src/helpers/check.ts

fix: darkMode tailwindcss config check

---

src/actions/upgrade-action.ts

fix: compare version about beta

---

src/actions/add-action.ts

Close https://github.com/nextui-org/nextui/issues/4240

fix: exit the process when all components added

---

src/constants/store.ts
src/index.ts
src/scripts/helpers.ts

fix: reduce fetch components

---

src/helpers/utils.ts

fix: upgrade peerDep version required min version

---

src/actions/add-action.ts
src/helpers/check.ts
src/helpers/type.ts

close #https://github.com/nextui-org/nextui/issues/4424

fix: add action will upgrade to required min peerDep version

---

packages/codemod/src/helpers/actions/migrate/migrate-common.ts
packages/codemod/src/helpers/actions/migrate/migrate-nextui-provider.ts

fix: migrate nextui provider change to use regex

---

packages/codemod/src/actions/migrate-action.ts
packages/codemod/src/constants/prefix.ts
packages/codemod/src/helpers/actions/migrate/migrate-left-files.ts
packages/codemod/src/helpers/find-files.ts
packages/codemod/src/helpers/utils.ts

1. Add new prompt to ask user whether to replace files which still remain `@nextui-org` content to `@heroui`
2. Add end note
3. Add dot files `.storybook` deceted

feat: add remaining files replace prompt and dot files detected and end note

---

packages/codemod/src/actions/migrate-action.ts
packages/codemod/src/helpers/actions/migrate/migrate-json.ts
packages/codemod/src/helpers/actions/migrate/migrate-left-files.ts
packages/codemod/src/helpers/https.ts
packages/codemod/src/helpers/utils.ts

1. Add reinstall prompt
- Yes -> reinstall
- No -> note need to reinstall manually 
2. Add default version when fetch error
3. Add retry fetch version

feat: add reinstall prompt and retry fetch version

---

packages/codemod/package.json

fix: codemod release

---

.npmrc
package.json
packages/codemod/package.json
pnpm-lock.yaml

Before
Will exit when select `yes`

fix: autocompleteMultiselect cancel exit when prompt yes

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/sync.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
package.json
packages/codemod/README.md
packages/codemod/package.json
src/constants/templates.ts
src/index.ts

chore: org renamed

---

src/constants/components.json

new components such as `number-input`, `toast`  are not upgraded by CLI due to the absence in this file.

chore(constants): update components

---

src/constants/components.json
src/constants/required.ts
src/helpers/actions/upgrade/get-libs-data.ts
src/helpers/actions/upgrade/upgrade-types.ts
src/helpers/condition-value.ts
src/helpers/package.ts
src/helpers/upgrade.ts
src/scripts/helpers.ts

fix: upgrade all should upgrade all heroui packages

---

.gitignore
src/constants/components.json

Reverts heroui-inc/heroui-cli#153

Revert "chore: remove trace components.json"

---

src/actions/upgrade-action.ts
src/helpers/upgrade.ts
src/index.ts
test/src/check/check-upgrade-action.spec.ts

fix: upgrade beta package wont upgrade @heroui/react package

---

src/constants/component.ts
src/constants/components.json
src/helpers/actions/add/get-peer-pakcage-version.ts
src/helpers/check.ts
test/src/check/check-required-content-installed.spec.ts

close https://github.com/heroui-inc/heroui/issues/4796

fix: add action tailwindcss version always install latest verion

---

CHANGELOG.md
package.json

* feat: add remix laravel template
* feat: update docs
* feat: readme update
* feat: update
* fix: typo

chore: release v1.2.3
